config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :employees, only: [:index, :show]
  devise_for :employees

  get 'sub_employees/:id', to: 'employees#sub_employees',    as: 'sub_employees'
  get 'employee/:id/add_task', to: 'employees#tasks',        as: 'employee_tasks'
  post 'employee/:id/add_task', to: 'employees#task_create', as: 'employee_task'

  root 'employees#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Tiene que ir class_name porque es la relacion especial que no se llama a si misma
  has_many :employees, class_name: "Employee", foreign_key: "boss_id"

  # Tiene que ir class_name porque es la relacion especial que no se llama a si misma
  # Ademas, recuerde que la columna boss_id es OPCIONAL. En caso de que alguien no tenga jefe.
  belongs_to :boss, class_name: "Employee", optional:true

  has_many :employee_tasks
  has_many :tasks, through: :employee_tasks

end

app/models/employee_task.rb
class EmployeeTask < ApplicationRecord
  belongs_to :task
  belongs_to :employee
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :employee_tasks
  has_many :employees, through: :employee_tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :picture])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, except: [:index]
  def index
    @employees = Employee.all.order(created_at: :asc)
  end

  def sub_employees
    @sub_employees = @employee.employees
    respond_to do |format|
      format.js
    end
  end

  def show
  end

  def tasks
    @tasks = Task.all.pluck(:title, :id)
  end

  def task_create
    @task = Task.find(params[:task_id])
    puts "###########"
    puts "###########"
    puts "###########"
    puts "###########"
    puts @task
    @employee.tasks << @task
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:content, :title, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/employees/_list_subemployees.html.erb
<div id="subemployees-<%= employee.id %>-level-<%= level %>">
  <%= link_to 'View employees',
    employee_subs_path(employee, level),
    remote: true,
    id: "subemployee-from-#{employee.id}",
    class: "my-3 ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-green-600 hover:bg-green-700" %>
    <div id="employee-<%= employee.id %>-subemployee-list"></div>
  <% sub_employees.each do |sub_employee| %>
    <div>
      <p><%= sub_employee.name %></p>
      <%= image_tag sub_employee.picture, size: '32x32' %>
    </div>
  <% end %>
</div>

app/views/employees/_mini_table_employees.html.erb
<table class="table-fixed">
  <thead>
    <tr>
      <td class="w-1/4">Foto</td>
      <td class="w-1/4">Email</td>
    </tr>
  </thead>
  <tbody>
    <% employees.each do |employee| %>
      <%= render 'view_employees_mini', employee: employee %>
    <% end %>
  </tbody>
</table>

app/views/employees/_select_boss.html.erb
<%= form_with(url: employee_boss_path(employee), local: false) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>

  </div>
  <%= form.select :boss_id, @employees, class: "form-input px-4 py-1 rounded-md" %>

  <div class="actions">
    <%= form.submit data: {disable_with: 'submitting...'},
      class: "my-3 ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-green-600 hover:bg-green-700"
      %>
  </div>
<% end %>

app/views/employees/_sub_employees.html.erb
<% sub_employees.each do |sub_employee| %>
  <div>
    <p><%= sub_employee.email %></p>
    <%= image_tag sub_employee.picture, size: '32x32' %>
  </div>
<% end %>

app/views/employees/_table_employee.html.erb
<tr class="bg-emerald-200">
  <td><%= employee.name %></td>
  <td><%= image_tag employee.picture, size: "64x64" %></td>
  <td><%= employee.email %></td>
  <td>
    <% if employee.boss.nil? %>
      <h1>No tiene</h1>
      <%= button_to 'Agregar jefe', employee_bosses_path(employee), remote: true, class: "my-3 ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700" %>
    <% else %>
      <%= image_tag employee.boss.picture, size: "32x32" %>
      <%= button_to 'Cambiar jefe', employee_bosses_path(employee), remote: true, class: "my-3 ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700" %>
    <% end %>
    <div
      class="bg-gray-200 rounded-md ring-1"
      id="employee-<%= employee.id %>-boss"></div>
  </td>
  <td>
    <%= render partial: 'employees/list_subemployees', locals: {employee: employee, sub_employees: [], level: 0} %>
  </td>
</tr>

app/views/employees/_view_employees.html.erb
<tr class="bg-emerald-200">
  <td><%= employee.employees.empty? ? "no jefe: #{employee.name}" : "<strong>JEFE #{employee.name}</strong>".html_safe %></td>
  <td><%= image_tag employee.picture, size: "64x64" %></td>
  <td><%= employee.email %></td>
  <td>
    <%= link_to 'Detalles', employee, class: "my-3 ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-green-600 hover:bg-green-700" %>
  </td>
  <td>
    <div id="container-sub-employees-<%= employee.id %>">
      <%= link_to 'Ver empleados', sub_employees_path(employee.id), remote: true, class: "my-3 ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700" %>
    </div>
  </td>
</tr>

app/views/employees/_view_employees_mini.html.erb
<tr class="bg-emerald-200">
  <td><%= image_tag employee.picture, size: "64x64" %></td>
  <td><%= employee.email %></td>
  <td>
    <div id="container-sub-employees-<%= employee.id %>">
      <%= link_to 'Ver empleados', sub_employees_path(employee.id), remote: true, class: "my-3 ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700" %>
    </div>
  </td>
</tr>

app/views/employees/add_boss.js.erb
console.log("Hi, I'm add_boss. Employee: ", <%= @employee.id %>)
var employee_select_box = document.querySelector('#employee-<%= @employee.id %>-boss')
<% if @employee.save %>
  employee_select_box.innerHTML = ''
<% else %>
  employee_select_box.innerHTML = "<%= escape_javascript(render partial: 'employees/select_boss', locals: {employee: @employee}) %>"
<% end %>

app/views/employees/bosses.js.erb
console.log("Hi, I'm Bosses. Employee: ", <%= @employee.id %>)

var employee_select_box = document.querySelector('#employee-<%= @employee.id %>-boss')
employee_select_box.innerHTML = "<%= escape_javascript(render partial: 'employees/select_boss', locals: {employee: @employee}) %>"
// employee_select_box.innerHTML = "<div>Bla bla bla</div>"

app/views/employees/index.html.erb
<div class="text-xl font-medium text-black">Empleados</div>

<%= render 'table_employees', employees: @employees %>

app/views/employees/show.html.erb
<div class="grid grid-cols-2 gap-4 my-5">
  <div>
    <%= image_tag @employee.picture, class: "inline-block h-20 w-20 rounded-full ring-2 ring-white" %>
    <div id="tasks-aggregator" class="my-5">
      <%= link_to 'Agregar tarea', employee_tasks_path(@employee), remote: true, class: "btn-indigo" %>
    </div>
  </div>
  <div class="my-5" id="table-tasks">
    <%= render 'tasks/table_tasks', tasks: @employee.tasks %>
  </div>
</div>

app/views/employees/sub_employees.js.erb
console.log("HOLA, SOY EMPLOYEE", '<%= j @employee.id %>')
var container_sub_employees = document.querySelector("#container-sub-employees-<%= @employee.id %>")


/*
<% @sub_employees.each do |sub_employee| %>
  var div_sub_employee = document.createElement('div')
  div_sub_employee.innerText = '<%= j sub_employee.email %>'

  container_sub_employees.appendChild(div_sub_employee)
<% end %>
  */


container_sub_employees
container_sub_employees.innerHTML = '<%= j render 'mini_table_employees', employees: @sub_employees %>'

app/views/employees/task_create.js.erb
console.log("Hurray, task was created")

var task_aggregator = document.querySelector('#tasks-aggregator')
task_aggregator.innerHTML = '<%= j link_to 'Agregar tarea', employee_tasks_path(@employee), remote: true, class: "btn-indigo" %>'

var table_tasks = document.querySelector('#table-tasks')
table_tasks.innerHTML = '<%= j render 'tasks/table_tasks', tasks: @employee.tasks %>'

app/views/employees/tasks.js.erb
console.log("HI, I'm tasks#index")


var tasks_aggregator = document.querySelector('#tasks-aggregator')

tasks_aggregator.innerHTML = '<%= j render partial: 'employees/add_task', locals: {employee: @employee, tasks: @tasks} %>'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdministracionEmpresa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application','data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container mx-auto">

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="relative bg-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
      <div class="flex justify-start lg:w-0 lg:flex-1">
        <%= link_to root_path do %>
          <span class="sr-only">Workflow</span>
          <%= image_tag "lambda.jpg", alt: "logo", class: "h-8 w-auto sm:h-10" %>
        <% end %>
        <div class="hidden md:flex items-center justify-start md:flex-1 lg:w-0">
          <%= link_to 'Employees', employees_path, class: "px-5 mx-5 whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900" %>
          <%= link_to 'Tasks', tasks_path, class: "px-5 mx-5 whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900" %>
        </div>
      </div>
      <div class="-mr-2 -my-2 md:hidden">
        <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
          <span class="sr-only">Open menu</span>
          <!-- Heroicon name: outline/menu -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </div>
      <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
        <% if employee_signed_in? %>
          <%= link_to 'Cerrar sesión', destroy_employee_session_path, method: :delete, class: 'ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700' %>
        <% else %>
          <%= link_to 'Iniciar sesión', new_employee_session_path, class: 'whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900' %>
          <%= link_to 'Registrarse', new_employee_registration_path, class: 'mx-5 btn-indigo' %>
        <% end %>
      </div>
    </div>
  </div>

  <!--
    Mobile menu, show/hide based on mobile menu state.

    Entering: "duration-200 ease-out"
      From: "opacity-0 scale-95"
      To: "opacity-100 scale-100"
    Leaving: "duration-100 ease-in"
      From: "opacity-100 scale-100"
      To: "opacity-0 scale-95"
  -->
  <div class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
    <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
      <div class="pt-5 pb-6 px-5">
        <div class="flex items-center justify-between">
          <div>
            <%= image_tag "lambda.jpg", alt: "logo", class: "h-8 w-auto" %>
          </div>
          <div class="-mr-2">
            <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
              <span class="sr-only">Close menu</span>
              <!-- Heroicon name: outline/x -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div class="mt-6">
        </div>
      </div>
      <div class="py-6 px-5 space-y-6">
        <div>
          <% if employee_signed_in? %>
            <%= link_to 'Cerrar sesión', destroy_employee_session_path, method: :delete, class: 'text-indigo-600 hover:text-indigo-500' %>
          <% else %>
            <%= link_to 'Sign up', new_employee_session_path, class: 'w-full flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700' %>
            <p class="mt-6 text-center text-base font-medium text-gray-500">
              Existing customer?
              <%= link_to 'Sign in', new_employee_registration_path, class: 'text-indigo-600 hover:text-indigo-500'%>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="mt-10 sm:mt-0">
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2">
      <%= form_with(model: task, local: false) do |form| %>
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <% if task.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

                  <ul>
                    <% task.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="col-span-6">
                <%= form.label :title, class: "block text-sm font-medium text-gray-700" %>
                <%= form.text_field :title, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </div>

              <div class="col-span-6">
                <%= form.label :content, class: "block text-sm font-medium text-gray-700" %>
                <%= form.text_area :content, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </div>

              <div class="col-span-6">
                <%= form.label :status, class: "block text-sm font-medium text-gray-700" %>
                <%= form.number_field :status, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </div>
            </div>
          </div>

          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            <%= form.submit data: {disable_with: 'submitting...'}, class: "btn-green" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="hidden sm:block" aria-hidden="true">
  <div class="py-5">
    <div class="border-t border-gray-200"></div>
  </div>
</div>

app/views/tasks/_table_tasks.html.erb
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Title</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Content</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
              <th colspan="3" scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"></th>
            </tr>
          </thead>

          <tbody class="bg-white divide-y divide-gray-200">
            <% tasks.each do |task| %>
              <tr>
                <td class="px-6 py-4 whitespace-nowrap"><%= task.title %></td>
                <td class="px-6 py-4 whitespace-nowrap"><%= task.content %></td>
                <td class="px-6 py-4 whitespace-nowrap"><%= task.status %></td>
                <td class="px-6 py-4 whitespace-nowrap"><%= link_to 'Show', task %></td>
                <td class="px-6 py-4 whitespace-nowrap"><%= link_to 'Edit', edit_task_path(task) %></td>
                <td class="px-6 py-4 whitespace-nowrap"><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-red' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.content %></td>
  <td><%= task.title %></td>
  <td><%= task.status %></td>
  <td><%= link_to 'Show', task %></td>
  <td><%= link_to 'Edit', edit_task_path(task) %></td>
  <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/tasks/create.js.erb
var elemento = document.querySelector('table tbody')
elemento.insertAdjacentHTML('beforeend', "<%= escape_javascript(render partial: 'tasks/task', locals: {task: @task}) %>")

var content = document.querySelector('#task-new')
content.innerHTML = '<%= link_to 'New Task', new_task_path, remote: true, class: "btn-indigo" %>'

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<div id="task-new" class="my-5" >
  <%= link_to 'New Task', new_task_path, remote: true, class: "btn-indigo" %>
</div>

<%= render 'table_tasks', tasks: @tasks %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
console.log("tasks#new")
var new_container = document.querySelector('#task-new')

new_container.innerHTML = '<%= j render partial: 'tasks/form', locals: {task: @task} %>'

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>